image: atlassian/default-image:3

definitions:
  steps:
    - step: &deploy
        name: deploy
        script:
          - pipe: atlassian/ssh-run:0.4.0
            variables:
              SSH_USER: $USER
              SERVER: $SERVER
              MODE: 'command'
              COMMAND:
                >-
                cd /var/www/${WORK_DIR:=dfs}/api &&
                git fetch --prune &&
                git checkout $BITBUCKET_BRANCH &&
                git pull &&
                cd ../docker &&
                docker-compose exec -T api composer install &&
                docker-compose exec -T api composer check-build &&
                docker-compose exec -T api php artisan down &&
                docker-compose exec -T api php artisan cache:clear &&
                docker-compose exec -T api php artisan config:cache &&
                docker-compose exec -T api php artisan route:cache &&
                docker-compose exec -T api php artisan l5-swagger:generate &&
                docker-compose exec -T api php artisan up &&
                docker-compose exec -T api php artisan test
pipelines:
  custom:
    deploy-to-dev:
      - step:
          <<: *deploy
          deployment: development
          name: deploy to dev
    deploy-to-stage:
      - step:
          <<: *deploy
          deployment: stage
          name: deploy to stage
  branches:
    develop:
      - step:
          <<: *deploy
          deployment: development
          name: deploy to dev
    master:
      - step:
          <<: *deploy
          deployment: development
          name: deploy to dev
    '{release/*}':
      - step:
          <<: *deploy
          deployment: development
          name: deploy to dev
