image: atlassian/default-image:3

definitions:
  steps:
    - step: &deploy
        name: deploy
        script:
          - pipe: atlassian/ssh-run:0.2.8
            variables:
              SSH_USER: $USER
              SERVER: $SERVER
              COMMAND:
                >-
                cd /var/www/dfs/api &&
                git fetch --prune &&
                git checkout $BITBUCKET_BRANCH &&
                git pull &&
                docker-compose exec -T api composer install &&
                docker-compose exec -T api composer check-build &&
                docker-compose exec -T api php artisan down &&
                docker-compose exec -T api php artisan cache:clear &&
                docker-compose exec -T api php artisan config:cache &&
                docker-compose exec -T api php artisan route:cache &&
                docker-compose exec -T api php artisan migrate &&
                docker-compose exec -T api php artisan up &&
                docker-compose exec -T api php artisan test
pipelines:
  pull-requests:
    '**':
      - step:
          <<: *deploy
          deployment: development
          name: deploy to development
  custom:
    deploy-to-dev:
      - step:
          <<: *deploy
          deployment: development
          name: deploy to development
  branches:
    develop:
      - step:
          <<: *deploy
          deployment: development
          name: deploy to dev server
    master:
      - step:
          <<: *deploy
          deployment: development
          name: deploy to dev server
    '{release/*}':
      - step:
          <<: *deploy
          deployment: development
          name: deploy to dev server
