version: "3.7"
services:
  api:
    build: ./docker/php
    container_name: das-app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - ${APP_PORT}:8000
    external_links:
      - db

networks:
  default:
    external:
      name: dfs-network
